[package]
name = "guessing_game_v2"
version = "0.1.0"
authors = ["q.chen <cqqccqc@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
